title: "MeRaGENE"
description: "MEtagenomics RApid hmm based GENE identification"
components:
  filter:
    title: "Filter"
    description: "Filter your data by using charts."
    icon: "icons/filter.svg"
  search:
    title: "Search"
    description: "View your data and search for specific values."
    icon: "icons/magnifier.svg"
  contact:
    title: "Contact"
    description: "Contact us if you questions or suggestions."
    icon: "icons/email.svg"
emails:
  - pbelmann@cebitec.uni-bielefeld.de
  - benedikt@cebitec.uni-bielefeld.de
  - wpaetzold@techfak.uni-bielefeld.de
repository: https://github.com/metagenomics/MeRaGENE/issues
scripts:
  - "js/d3.min.js"
  - "js/jquery.js"
  - "js/bootstrap.min.js"
  - "js/bootstrap-table.min.js"
  - "js/c3.min.js"
  - "js/buildTable.js"
  - "js/bootstrap-table-filter-control.js"
  - "js/pileup.js"
css:
  - "css/bootstrap.min.css"
  - "css/bootstrap-table.min.css"
  - "css/c3.min.css"
  - "css/style.css"
  - "css/pileup.css"
